#!/usr/bin/env bash
set -ex

HERE=$(dirname $0)
. $HERE/common

docker build --pull \
       --tag $TAG_SHA \
       -f docker/Dockerfile \
       $PACKAGE_ROOT

# We always push the SHA tagged versions, for debugging if the tests
# after this step fail
docker push $TAG_SHA
